name: CI for Image Build

on:
  pull_request:
    types: [closed]
    branches:
          - main

jobs:
  
    build:
        name: Image Build
        runs-on: ubuntu-latest
       
        steps:
             - name: Checkout Repository
               uses: actions/checkout@v2

             - name: Create zip file
               run: |
                zip -r webapp.zip .
                echo $(pwd)

            
            #  - name: Create env file
            #    run: |
            #     touch .env
            #     echo "PORT=3000" >> .env
            #     echo "DATABASE=trial_db" >> .env
            #     echo "DB_USERNAME=root" >> .env
            #     echo "PASSWORD=Cloud@123" >> .env
            #     echo "HOST=localhost" >> .env
          

             - name: Install Packer
               run: |
                  wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
                  unzip packer_1.7.5_linux_amd64.zip
                  sudo mv packer /usr/local/bin/
        
             - name: Run `packer init`
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  packer init packer 

             - name: Authenticate with GCP
               uses: google-github-actions/auth@v2
               with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
       
             - name: Build Packer Image
               id: packer_build
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  packer build -except=manifest packer

             - name: GET GCP IMAGE ID
               id: get_image_id
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  IMAGE_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
                  echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
                  echo "Built GCP image ID is $IMAGE_ID"
                   
             - name: Generate version number
               id: versioning
               run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

             - name: Generate updated instance template
               run: |
                gcloud compute instance-templates create "my-template-${{ env.VERSION }}" \
                 --image "${{ env.IMAGE_ID }}" \
                 --machine-type "e2-standard-2" \
                 --region "us-east1" \
                 --tags "webapp" \
                 --disk "auto-delete=false,disk-size=40GB,disk-type=pd-ssd" \
                 --network-interface "vpc,webapp_subnet" \
                 --service-account "email=logger-sa-assignment06@cloudassignment03-413923.iam.gserviceaccount.com,scopes=cloud-platform,pubsub" \
                 --lifecycle "create-before-destroy"
                 --metadata "startup-script=$(cat <<EOF
                      #!/bin/bash
                      sudo bash -c 'cat <<EOF > /opt/webappUnzipped/Dipti_Shevalekar_002245703_01/.env
                      DB_USERNAME="webapp"
                      DATABASE="csye6225"
                      PASSWORD="rH7IsHSIPTDa4mZX"
                      HOST="10.0.160.2"
                      PORT=3000
                      EOF'
                      sudo chown -R csye6225:csye6225 opt/webappUnzipped/Dipti_Shevalekar_002245703_01
                      sudo chmod -R 755 opt/webappUnzipped/Dipti_Shevalekar_002245703_01
                      sudo systemctl restart systemdSetup.service
                      EOF
                      )" \
                 echo the instance was updated successfully
