name: CI for Image Build

on:
  pull_request:
    types: [closed]
    branches:
          - main

jobs:
  
    build:
        name: Image Build
        runs-on: ubuntu-latest
       
        steps:
             - name: Checkout Repository
               uses: actions/checkout@v2

             - name: Create zip file
               run: |
                zip -r webapp.zip .
                echo $(pwd)

            
             - name: Create env file
               run: |
                touch .env
                echo "PORT=3000" >> .env
                echo "DATABASE=trial_db" >> .env
                echo "DB_USERNAME=root" >> .env
                echo "PASSWORD=Cloud@123" >> .env
                echo "HOST=localhost" >> .env
          

             - name: Install Packer
               run: |
                  wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
                  unzip packer_1.7.5_linux_amd64.zip
                  sudo mv packer /usr/local/bin/
        
             - name: Run `packer init`
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  packer init packer 

             - name: Authenticate with GCP
               uses: google-github-actions/auth@v2
               with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
       
             - name: build packer
               run: |
                   cd Dipti_Shevalekar_002245703_01
                   packer build packer

