on:
  pull_request:
    branches:
      - main
  workflow_dispatch :

jobs:
  build:
    name: CI for Packer Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Web App
        run: zip -r webapp.zip ../webapp

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
          unzip packer_1.7.5_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run `packer init`
        run: |
          cd Dipti_Shevalekar_002245703_01/packer
          packer init gcp.pkr.hcl

      - name: Run 'packer fmt'
        run: |
            cd Dipti_Shevalekar_002245703_01/packer
            packer fmt gcp.pkr.hcl

      - name : run validate
        run:
          cd  Dipti_Shevalekar_002245703_01/packer
          packer validate gcp.pkr.hcl
        


     

 


