name: CI for Image Build

on:
  pull_request:
    types: [closed]
    branches:
          - main

jobs:
  
    build:
        name: Image Build
        runs-on: ubuntu-latest
       
        steps:
             - name: Checkout Repository
               uses: actions/checkout@v2

             - name: Create zip file
               run: |
                zip -r webapp.zip .
                echo $(pwd)

            
            #  - name: Create env file
            #    run: |
            #     touch .env
            #     echo "PORT=3000" >> .env
            #     echo "DATABASE=trial_db" >> .env
            #     echo "DB_USERNAME=root" >> .env
            #     echo "PASSWORD=Cloud@123" >> .env
            #     echo "HOST=localhost" >> .env
          

             - name: Install Packer
               run: |
                  wget https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip
                  unzip packer_1.7.5_linux_amd64.zip
                  sudo mv packer /usr/local/bin/
        
             - name: Run `packer init`
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  packer init packer 

             - name: Authenticate with GCP
               uses: google-github-actions/auth@v2
               with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
       
             - name: Build Packer Image
               id: packer_build
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  packer build -except=manifest packer

             - name: GET GCP IMAGE ID
               id: get_image_id
               run: |
                  cd Dipti_Shevalekar_002245703_01
                  IMAGE_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
                  echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
                  echo "Built GCP image ID is $IMAGE_ID"
                   
             - name: Generate version number
               id: versioning
               run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

             - name: Generate updated instance template
               run: |
                gcloud compute instance-templates create my-template-${{ env.VERSION }} \
                --project=$PROJECT_ID \
                --description="$IT_TEMPLATE_DESCRIPTION" \
                --machine-type="$VIRTUAL_MACHINE_TYPE" \
                --network-interface="network-tier=PREMIUM,subnet=webapp" \
                --maintenance-policy="$MAINTENANCE_POLICY" \
                --service-account="$SERVICE_ACCOUNT" \
                --scopes="$SCOPES" \
                --region="$REGION" \
                --tags="$VM_TAG" \
                --create-disk="auto-delete=$IT_DISK_AUTO_DELETE,boot=$IT_DISK_BOOT,image=projects/cloudassignment03-413923/global/images/$IMAGE_ID,mode=rw,size=$VIRTUAL_MACHINE_DISK_SIZE_GB,type=$VIRTUAL_MACHINE_DISK_TYPE" \
                --no-shielded-secure-boot \
                --shielded-vtpm \
                --shielded-integrity-monitoring \
                --reservation-affinity=none
                env:
                  PROJECT_ID: ${{secrets.Project_ID}}
                  IT_TEMPLATE_DESCRIPTION : ${{secrets.IT_TEMPLATE_DESCRIPTION}} 
                  VIRTUAL_MACHINE_TYPE: ${{secrets.VIRTUAL_MACHINE_TYPE}}
                  REGION: ${{secrets.REGION}}
                  MAINTENANCE_POLICY: ${{secrets.MAINTENANCE_POLICY}}
                  PROVISIONING_MODEL: ${{secrets.PROVISIONING_MODEL}}
                  SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}
                  SCOPES: ${{secrets.SCOPES}}
                  VM_TAG: ${{ secrets.VM_TAG }}
                  VIRTUAL_MACHINE_IMAGE: ${{secrets.PACKER_BUILD_IMAGE_ID}}
                  VIRTUAL_MACHINE_DISK_SIZE_GB: ${{ secrets.VIRTUAL_MACHINE_DISK_SIZE_GB }}
                  VIRTUAL_MACHINE_DISK_TYPE: ${{ secrets.VIRTUAL_MACHINE_DISK_TYPE }}
                  IT_DISK_AUTO_DELETE: ${{ secrets.IT_DISK_AUTO_DELETE }}
                  IT_DISK_BOOT: ${{ secrets.IT_DISK_BOOT }}
                 echo the instance was updated successfully
