name : CI for Test

on :
    pull_request :
     branches :
        - main
    workflow_dispatch :
jobs :
    build :
        name : integration-test
        runs-on : ubuntu-latest

        steps :
            - name  : checkout code 
              uses : actions/checkout/@v3